---
- name:  Установка filebeat
  hosts: webservers
  become: yes
  vars:
    kibana_host: 10.0.1.5:5601
    elastic_host: 10.0.2.4:9200
  tasks:
    - name: Установка java
      apt:
        name: default-jre
        state: latest
    - name: Установка filebeat
      apt:
        deb: https://mirror.yandex.ru/mirrors/elastic/9/pool/main/f/filebeat/filebeat-9.2.1-amd64.deb
    - name: Копирование настроек
      template:
        src: ./filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
    - name: systemd daemon-reload
      systemd:
        daemon_reload: true
    - name: Запуск filebeat
      service:
        name: filebeat
        state: restarted
        enabled: true