---
- name: Установка Kibana
  hosts: kibana
  become: yes
  vars:
    elastic_host: 10.0.2.4:9200
  tasks:
    - name: Установка java
      apt:
        name: default-jre
        state: latest
    - name: Установка Kibana
      apt:
        deb: https://mirror.yandex.ru/mirrors/elastic/9/pool/main/k/kibana/kibana-9.2.1-amd64.deb
    - name: Копирование настроек
      template:
        src: ./kibana.yml.j2
        dest: /etc/kibana/kibana.yml
    - name: systemd daemon-reload
      systemd:
        daemon_reload: true
    - name: Запуск Kibana
      service:
        name: kibana
        state: restarted
        enabled: true